# Generated by Django 2.1 on 2018-08-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('address', models.CharField(max_length=50, unique=True, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('metro', models.CharField(max_length=50, verbose_name='Метро')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('time', models.CharField(max_length=50, verbose_name='Время работы')),
                ('time_weekend', models.CharField(blank=True, max_length=50, null=True, verbose_name='Время работы в выходные')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Иконка')),
            ],
        ),
    ]
