# Generated by Django 2.1 on 2018-08-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('url', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('icon', models.ImageField(unique=True, upload_to='media/', verbose_name='Иконка')),
            ],
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.RenameField(
            model_name='address',
            old_name='image',
            new_name='icon',
        ),
    ]
