# Generated by Django 2.1 on 2018-08-11 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20180811_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'социальную сеть', 'verbose_name_plural': 'Социальные сети'},
        ),
    ]
