# Generated by Django 2.1 on 2018-08-11 18:49

from django.db import migrations, models
import landing.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20180811_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.FileField(unique=True, upload_to='media/', validators=[landing.models.validate_svg], verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='social',
            name='url',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ссылка'),
        ),
    ]
