# Generated by Django 2.1 on 2018-08-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20180811_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.ImageField(unique=True, upload_to='media/', verbose_name='Иконка'),
        ),
    ]
