# Generated by Django 2.1 on 2018-08-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20180811_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='icon',
            field=models.ImageField(upload_to='', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.ImageField(unique=True, upload_to='', verbose_name='Иконка'),
        ),
    ]
