# Generated by Django 2.1 on 2018-08-11 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_menu_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.Event'),
        ),
        migrations.AddField(
            model_name='product',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.Menu'),
        ),
    ]
