# Generated by Django 2.1 on 2018-08-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_auto_20180811_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='special',
        ),
        migrations.AddField(
            model_name='menu',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
