# Generated by Django 2.1 on 2018-08-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_auto_20180811_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.CharField(max_length=50, null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=50, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=50, null=True, verbose_name='Вес, г.'),
        ),
    ]
