# Generated by Django 2.1 on 2018-08-16 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_auto_20180816_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
