# Generated by Django 2.1 on 2018-08-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_auto_20180816_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='corporate', verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='title', max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
