# Generated by Django 2.1 on 2018-08-24 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing', '0016_auto_20180821_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('guests', models.IntegerField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.Address')),
            ],
            options={
                'verbose_name': 'бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
